name: action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      env:
          SITE: ${{ matrix.site }}
          DATACENTER: ${{ matrix.datacenter }}
      run:
        shell: msys2 {0}
    strategy:
      matrix:
       include:
         - node-version: 10.x
           site: "prod"
           datacenter: "site-a"
         - node-version: 12.x
           site: "dev"
           datacenter: "site-b"
    steps:
      - name: Echo site details
        run: echo $SITE $DATACENTER
